// <auto-generated />
namespace OnlineBusReservationV6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class latestchangein27042018 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(latestchangein27042018));
        
        string IMigrationMetadata.Id
        {
            get { return "201804270346591_latestchangein27042018"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
